//ZAIDIMAS
export const GET_GRID_SUCCESS = 'GET_GRID_SUCCESS'
export const GET_GRID_FAILURE = 'GET_GRID_FAILURE'

//LAIKAS
export const START_MAIN_TIMER = 'START_MAIN_TIMER'
export const UPDATE_MAIN_TIMER = 'UPDATE_MAIN_TIMER'
export const STOP_MAIN_TIMER = 'STOP_MAIN_TIMER'

//ANSWERS
export const CORRECT_ANSWER = 'CORRECT_ANSWER'
export const WRONG_ANSWER = 'WRONG_ANSWER'

//ZAIDIMAS BAIGTAS
export const GAME_ENDED = 'GAME_ENDED'

//ZAIDIMO LYGIU KONSTANTOS
export const ADVANCE_LEVEL = 'ADVANCE_LEVEL'
export const HALT_NEXT_LEVEL = 'HALT_NEXT_LEVEL'
export const NEXT_LEVEL = 'NEXT_LEVEL'

//ZAIDIMO MAIN NUSTAMYMAS I DEFAULT => FALSE arba 0
export const SET_MAIN_VALUES_SUCCESS = 'SET_MAIN_VALUES_SUCCESS'


export const RESTART_GAME = 'RESTART_GAME'



//TESTING
export const START_BLOCK_TIMER = 'START_BLOCK_TIMER'
export const UPDATE_BLOCK_TIMER = 'UPDATE_BLOCK_TIMER'
export const STOP_BLOCK_TIMER = 'STOP_BLOCK_TIMER'


//TESTING 2
export const UPDATE_COMBO_AND_BLOCK_TIMER = 'UPDATE_COMBO_AND_BLOCK_TIMER'

